### ISSUE TITLE
Make FDC selectable for MSX2 which has no disk drive

### ISSUE THREAD

**Issue by juntaesu** [MiSTer-devel/MSX1_MiSTer#10]
I appreciate active development of this great MSX core. :)

In new MSX1 core (June 11 2023),
Currently FDC as SLOT is only selectable for MSX1.
Some MSX2s have no floppy drive. It's Daewoo CPC-300, Panasonic FS-A1 and many others.
Can you make FDC selectable for this type of MSX2?

If It's not easy to modify, you can ignore this. I'll use MSX2 machine which has the disk drive.

**Comment by tdlabac** [comment]
The ability to select FDC is now not conditional on MSX1, but on the specific MSX model. If the FDC is not part of the basic equipment of the selected MSX model, it is possible to select an external FDC
