### ISSUE TITLE
SCC/SCC+ audio missing channels in latest MSX2Test

### ISSUE THREAD

**Issue by MP2E** [MiSTer-devel/MSX1_MiSTer#9]
Thank you for all the great work on this core!

I noticed the latest test build has broken SCC audio, some of the channels appear to be missing in Metal Gear 2, Space Manbow, and SD Snatcher.

**Comment by tdlabac** [comment]
Fix in commit cebba1d83dc4b76836e8773cd7de1753bf2b14a6
